"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента. 

    The version of the OpenAPI document: 1.1.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from datetime import datetime
from pydantic import Field, StrictInt, StrictStr, field_validator
from typing import Optional
from typing_extensions import Annotated
from botix.models.messages_bulk_send200_response import MessagesBulkSend200Response
from botix.models.messages_bulk_send_request import MessagesBulkSendRequest
from botix.models.messages_list200_response import MessagesList200Response
from botix.models.messages_send200_response import MessagesSend200Response
from botix.models.messages_send_request import MessagesSendRequest

from botix.api_client import ApiClient, RequestSerialized
from botix.api_response import ApiResponse
from botix.rest import RESTResponseType


class MessagesApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def messages_bulk_send(
        self,
        messages_bulk_send_request: MessagesBulkSendRequest,
        idempotency_key: Annotated[Optional[Annotated[str, Field(strict=True, max_length=255)]], Field(description="Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MessagesBulkSend200Response:
        """Массовая отправка сообщений (v1.1)

        Отправляет до 50 сообщений одним запросом. Каждое — независимо: частичный успех допустим. Результат каждого item — либо `message_id` (успех), либо `error`.  Per-channel rate-limit (Telegram 30 msg/sec и т.п.) **не обходится** — если канал отвергает сообщение из-за своего лимита, item помечается `DELIVERY_FAILED`.  Поддерживает `Idempotency-Key`. 

        :param messages_bulk_send_request: (required)
        :type messages_bulk_send_request: MessagesBulkSendRequest
        :param idempotency_key: Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. 
        :type idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_bulk_send_serialize(
            messages_bulk_send_request=messages_bulk_send_request,
            idempotency_key=idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesBulkSend200Response",
            '400': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def messages_bulk_send_with_http_info(
        self,
        messages_bulk_send_request: MessagesBulkSendRequest,
        idempotency_key: Annotated[Optional[Annotated[str, Field(strict=True, max_length=255)]], Field(description="Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MessagesBulkSend200Response]:
        """Массовая отправка сообщений (v1.1)

        Отправляет до 50 сообщений одним запросом. Каждое — независимо: частичный успех допустим. Результат каждого item — либо `message_id` (успех), либо `error`.  Per-channel rate-limit (Telegram 30 msg/sec и т.п.) **не обходится** — если канал отвергает сообщение из-за своего лимита, item помечается `DELIVERY_FAILED`.  Поддерживает `Idempotency-Key`. 

        :param messages_bulk_send_request: (required)
        :type messages_bulk_send_request: MessagesBulkSendRequest
        :param idempotency_key: Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. 
        :type idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_bulk_send_serialize(
            messages_bulk_send_request=messages_bulk_send_request,
            idempotency_key=idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesBulkSend200Response",
            '400': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def messages_bulk_send_without_preload_content(
        self,
        messages_bulk_send_request: MessagesBulkSendRequest,
        idempotency_key: Annotated[Optional[Annotated[str, Field(strict=True, max_length=255)]], Field(description="Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Массовая отправка сообщений (v1.1)

        Отправляет до 50 сообщений одним запросом. Каждое — независимо: частичный успех допустим. Результат каждого item — либо `message_id` (успех), либо `error`.  Per-channel rate-limit (Telegram 30 msg/sec и т.п.) **не обходится** — если канал отвергает сообщение из-за своего лимита, item помечается `DELIVERY_FAILED`.  Поддерживает `Idempotency-Key`. 

        :param messages_bulk_send_request: (required)
        :type messages_bulk_send_request: MessagesBulkSendRequest
        :param idempotency_key: Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. 
        :type idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_bulk_send_serialize(
            messages_bulk_send_request=messages_bulk_send_request,
            idempotency_key=idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesBulkSend200Response",
            '400': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _messages_bulk_send_serialize(
        self,
        messages_bulk_send_request,
        idempotency_key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if idempotency_key is not None:
            _header_params['Idempotency-Key'] = idempotency_key
        # process the form parameters
        # process the body parameter
        if messages_bulk_send_request is not None:
            _body_params = messages_bulk_send_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/public/v1/messages/bulk-send',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def messages_list(
        self,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры `page`/`per_page` игнорируются. Получите следующий cursor из `meta.next_cursor` предыдущего ответа. `null`/отсутствие `next_cursor` = последняя страница. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (`?cursor=...`); для классической page-пагинации применяется `per_page`. ")] = None,
        contact_id: Optional[StrictInt] = None,
        chat_id: Annotated[Optional[StrictInt], Field(description="alias для conversation_id")] = None,
        channel: Optional[StrictStr] = None,
        role: Optional[StrictStr] = None,
        since: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MessagesList200Response:
        """История сообщений


        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param cursor: v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры `page`/`per_page` игнорируются. Получите следующий cursor из `meta.next_cursor` предыдущего ответа. `null`/отсутствие `next_cursor` = последняя страница. 
        :type cursor: str
        :param limit: v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (`?cursor=...`); для классической page-пагинации применяется `per_page`. 
        :type limit: int
        :param contact_id:
        :type contact_id: int
        :param chat_id: alias для conversation_id
        :type chat_id: int
        :param channel:
        :type channel: str
        :param role:
        :type role: str
        :param since:
        :type since: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_list_serialize(
            page=page,
            per_page=per_page,
            cursor=cursor,
            limit=limit,
            contact_id=contact_id,
            chat_id=chat_id,
            channel=channel,
            role=role,
            since=since,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesList200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def messages_list_with_http_info(
        self,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры `page`/`per_page` игнорируются. Получите следующий cursor из `meta.next_cursor` предыдущего ответа. `null`/отсутствие `next_cursor` = последняя страница. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (`?cursor=...`); для классической page-пагинации применяется `per_page`. ")] = None,
        contact_id: Optional[StrictInt] = None,
        chat_id: Annotated[Optional[StrictInt], Field(description="alias для conversation_id")] = None,
        channel: Optional[StrictStr] = None,
        role: Optional[StrictStr] = None,
        since: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MessagesList200Response]:
        """История сообщений


        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param cursor: v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры `page`/`per_page` игнорируются. Получите следующий cursor из `meta.next_cursor` предыдущего ответа. `null`/отсутствие `next_cursor` = последняя страница. 
        :type cursor: str
        :param limit: v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (`?cursor=...`); для классической page-пагинации применяется `per_page`. 
        :type limit: int
        :param contact_id:
        :type contact_id: int
        :param chat_id: alias для conversation_id
        :type chat_id: int
        :param channel:
        :type channel: str
        :param role:
        :type role: str
        :param since:
        :type since: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_list_serialize(
            page=page,
            per_page=per_page,
            cursor=cursor,
            limit=limit,
            contact_id=contact_id,
            chat_id=chat_id,
            channel=channel,
            role=role,
            since=since,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesList200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def messages_list_without_preload_content(
        self,
        page: Optional[Annotated[int, Field(strict=True, ge=1)]] = None,
        per_page: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = None,
        cursor: Annotated[Optional[StrictStr], Field(description="v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры `page`/`per_page` игнорируются. Получите следующий cursor из `meta.next_cursor` предыдущего ответа. `null`/отсутствие `next_cursor` = последняя страница. ")] = None,
        limit: Annotated[Optional[Annotated[int, Field(le=100, strict=True, ge=1)]], Field(description="v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (`?cursor=...`); для классической page-пагинации применяется `per_page`. ")] = None,
        contact_id: Optional[StrictInt] = None,
        chat_id: Annotated[Optional[StrictInt], Field(description="alias для conversation_id")] = None,
        channel: Optional[StrictStr] = None,
        role: Optional[StrictStr] = None,
        since: Optional[datetime] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """История сообщений


        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param cursor: v1.1+. Opaque cursor для постраничной выборки. Если передан — параметры `page`/`per_page` игнорируются. Получите следующий cursor из `meta.next_cursor` предыдущего ответа. `null`/отсутствие `next_cursor` = последняя страница. 
        :type cursor: str
        :param limit: v1.1+. Размер cursor-страницы. Используется только в cursor-режиме (`?cursor=...`); для классической page-пагинации применяется `per_page`. 
        :type limit: int
        :param contact_id:
        :type contact_id: int
        :param chat_id: alias для conversation_id
        :type chat_id: int
        :param channel:
        :type channel: str
        :param role:
        :type role: str
        :param since:
        :type since: datetime
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_list_serialize(
            page=page,
            per_page=per_page,
            cursor=cursor,
            limit=limit,
            contact_id=contact_id,
            chat_id=chat_id,
            channel=channel,
            role=role,
            since=since,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesList200Response",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _messages_list_serialize(
        self,
        page,
        per_page,
        cursor,
        limit,
        contact_id,
        chat_id,
        channel,
        role,
        since,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if page is not None:
            
            _query_params.append(('page', page))
            
        if per_page is not None:
            
            _query_params.append(('per_page', per_page))
            
        if cursor is not None:
            
            _query_params.append(('cursor', cursor))
            
        if limit is not None:
            
            _query_params.append(('limit', limit))
            
        if contact_id is not None:
            
            _query_params.append(('contact_id', contact_id))
            
        if chat_id is not None:
            
            _query_params.append(('chat_id', chat_id))
            
        if channel is not None:
            
            _query_params.append(('channel', channel))
            
        if role is not None:
            
            _query_params.append(('role', role))
            
        if since is not None:
            if isinstance(since, datetime):
                _query_params.append(
                    (
                        'since',
                        since.strftime(
                            self.api_client.configuration.datetime_format
                        )
                    )
                )
            else:
                _query_params.append(('since', since))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/public/v1/messages',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def messages_send(
        self,
        messages_send_request: MessagesSendRequest,
        idempotency_key: Annotated[Optional[Annotated[str, Field(strict=True, max_length=255)]], Field(description="Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> MessagesSend200Response:
        """Отправить сообщение

        Реально отправляет сообщение в канал (Telegram/widget/VK) и фиксирует его в истории. Канал выбирается так: 1. явный `channel` в payload (если передан); 2. `last_channel` контакта; 3. иначе 422 `NO_CHANNEL_AVAILABLE`.  Поддерживается заголовок `Idempotency-Key` (стандарт Stripe): повторный запрос с тем же ключом в течение 24 часов вернёт сохранённый ответ без новой отправки. Ответ будет содержать заголовок `Idempotent-Replayed: 1`. 

        :param messages_send_request: (required)
        :type messages_send_request: MessagesSendRequest
        :param idempotency_key: Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. 
        :type idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_send_serialize(
            messages_send_request=messages_send_request,
            idempotency_key=idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesSend200Response",
            '422': "Error",
            '502': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def messages_send_with_http_info(
        self,
        messages_send_request: MessagesSendRequest,
        idempotency_key: Annotated[Optional[Annotated[str, Field(strict=True, max_length=255)]], Field(description="Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[MessagesSend200Response]:
        """Отправить сообщение

        Реально отправляет сообщение в канал (Telegram/widget/VK) и фиксирует его в истории. Канал выбирается так: 1. явный `channel` в payload (если передан); 2. `last_channel` контакта; 3. иначе 422 `NO_CHANNEL_AVAILABLE`.  Поддерживается заголовок `Idempotency-Key` (стандарт Stripe): повторный запрос с тем же ключом в течение 24 часов вернёт сохранённый ответ без новой отправки. Ответ будет содержать заголовок `Idempotent-Replayed: 1`. 

        :param messages_send_request: (required)
        :type messages_send_request: MessagesSendRequest
        :param idempotency_key: Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. 
        :type idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_send_serialize(
            messages_send_request=messages_send_request,
            idempotency_key=idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesSend200Response",
            '422': "Error",
            '502': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def messages_send_without_preload_content(
        self,
        messages_send_request: MessagesSendRequest,
        idempotency_key: Annotated[Optional[Annotated[str, Field(strict=True, max_length=255)]], Field(description="Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. ")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Отправить сообщение

        Реально отправляет сообщение в канал (Telegram/widget/VK) и фиксирует его в истории. Канал выбирается так: 1. явный `channel` в payload (если передан); 2. `last_channel` контакта; 3. иначе 422 `NO_CHANNEL_AVAILABLE`.  Поддерживается заголовок `Idempotency-Key` (стандарт Stripe): повторный запрос с тем же ключом в течение 24 часов вернёт сохранённый ответ без новой отправки. Ответ будет содержать заголовок `Idempotent-Replayed: 1`. 

        :param messages_send_request: (required)
        :type messages_send_request: MessagesSendRequest
        :param idempotency_key: Уникальный токен запроса для защиты от дублей при сетевых сбоях. Рекомендация — UUID v4 на каждую логическую операцию. **TTL ключа — 24 часа.** После истечения тот же `Idempotency-Key` создаст новую операцию, кешированный результат не возвращается. Повтор в окне 24 часов вернёт сохранённый ответ + заголовок `Idempotent-Replayed: 1`. 
        :type idempotency_key: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._messages_send_serialize(
            messages_send_request=messages_send_request,
            idempotency_key=idempotency_key,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "MessagesSend200Response",
            '422': "Error",
            '502': "Error",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _messages_send_serialize(
        self,
        messages_send_request,
        idempotency_key,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if idempotency_key is not None:
            _header_params['Idempotency-Key'] = idempotency_key
        # process the form parameters
        # process the body parameter
        if messages_send_request is not None:
            _body_params = messages_send_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/public/v1/messages',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


