# coding: utf-8

# flake8: noqa

"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены. 

    The version of the OpenAPI document: 1.0.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ChannelsApi",
    "ChatsApi",
    "ContactsApi",
    "MessagesApi",
    "ScenariosApi",
    "SystemApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Channel",
    "ChannelsList200Response",
    "ChannelsList200ResponseMeta",
    "Chat",
    "ChatsList200Response",
    "Contact",
    "ContactWritable",
    "ContactsAddTag200Response",
    "ContactsAddTag200ResponseData",
    "ContactsAddTagRequest",
    "ContactsList200Response",
    "ContactsRemoveTag200Response",
    "Error",
    "ErrorError",
    "MeResponse",
    "MeResponseData",
    "MeResponseDataLimits",
    "MeResponseDataRateLimit",
    "Message",
    "MessagesList200Response",
    "MessagesSend200Response",
    "MessagesSend200ResponseData",
    "MessagesSendRequest",
    "MessagesSendRequestAttachmentsInner",
    "Scenario",
    "ScenariosList200Response",
    "ScenariosRun200Response",
    "ScenariosRun200ResponseData",
    "ScenariosRunRequest",
    "SuccessContact",
    "SuccessWithMeta",
    "SuccessWithMetaMeta",
    "Webhook",
    "WebhookEvent",
    "WebhooksCreate201Response",
    "WebhooksCreate201ResponseData",
    "WebhooksCreateRequest",
    "WebhooksList200Response",
    "WebhooksTest200Response",
    "WebhooksTest200ResponseData",
    "WebhooksUpdateRequest",
]

# import apis into sdk package
from botix.api.channels_api import ChannelsApi as ChannelsApi
from botix.api.chats_api import ChatsApi as ChatsApi
from botix.api.contacts_api import ContactsApi as ContactsApi
from botix.api.messages_api import MessagesApi as MessagesApi
from botix.api.scenarios_api import ScenariosApi as ScenariosApi
from botix.api.system_api import SystemApi as SystemApi
from botix.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from botix.api_response import ApiResponse as ApiResponse
from botix.api_client import ApiClient as ApiClient
from botix.configuration import Configuration as Configuration
from botix.exceptions import OpenApiException as OpenApiException
from botix.exceptions import ApiTypeError as ApiTypeError
from botix.exceptions import ApiValueError as ApiValueError
from botix.exceptions import ApiKeyError as ApiKeyError
from botix.exceptions import ApiAttributeError as ApiAttributeError
from botix.exceptions import ApiException as ApiException

# import models into sdk package
from botix.models.channel import Channel as Channel
from botix.models.channels_list200_response import ChannelsList200Response as ChannelsList200Response
from botix.models.channels_list200_response_meta import ChannelsList200ResponseMeta as ChannelsList200ResponseMeta
from botix.models.chat import Chat as Chat
from botix.models.chats_list200_response import ChatsList200Response as ChatsList200Response
from botix.models.contact import Contact as Contact
from botix.models.contact_writable import ContactWritable as ContactWritable
from botix.models.contacts_add_tag200_response import ContactsAddTag200Response as ContactsAddTag200Response
from botix.models.contacts_add_tag200_response_data import ContactsAddTag200ResponseData as ContactsAddTag200ResponseData
from botix.models.contacts_add_tag_request import ContactsAddTagRequest as ContactsAddTagRequest
from botix.models.contacts_list200_response import ContactsList200Response as ContactsList200Response
from botix.models.contacts_remove_tag200_response import ContactsRemoveTag200Response as ContactsRemoveTag200Response
from botix.models.error import Error as Error
from botix.models.error_error import ErrorError as ErrorError
from botix.models.me_response import MeResponse as MeResponse
from botix.models.me_response_data import MeResponseData as MeResponseData
from botix.models.me_response_data_limits import MeResponseDataLimits as MeResponseDataLimits
from botix.models.me_response_data_rate_limit import MeResponseDataRateLimit as MeResponseDataRateLimit
from botix.models.message import Message as Message
from botix.models.messages_list200_response import MessagesList200Response as MessagesList200Response
from botix.models.messages_send200_response import MessagesSend200Response as MessagesSend200Response
from botix.models.messages_send200_response_data import MessagesSend200ResponseData as MessagesSend200ResponseData
from botix.models.messages_send_request import MessagesSendRequest as MessagesSendRequest
from botix.models.messages_send_request_attachments_inner import MessagesSendRequestAttachmentsInner as MessagesSendRequestAttachmentsInner
from botix.models.scenario import Scenario as Scenario
from botix.models.scenarios_list200_response import ScenariosList200Response as ScenariosList200Response
from botix.models.scenarios_run200_response import ScenariosRun200Response as ScenariosRun200Response
from botix.models.scenarios_run200_response_data import ScenariosRun200ResponseData as ScenariosRun200ResponseData
from botix.models.scenarios_run_request import ScenariosRunRequest as ScenariosRunRequest
from botix.models.success_contact import SuccessContact as SuccessContact
from botix.models.success_with_meta import SuccessWithMeta as SuccessWithMeta
from botix.models.success_with_meta_meta import SuccessWithMetaMeta as SuccessWithMetaMeta
from botix.models.webhook import Webhook as Webhook
from botix.models.webhook_event import WebhookEvent as WebhookEvent
from botix.models.webhooks_create201_response import WebhooksCreate201Response as WebhooksCreate201Response
from botix.models.webhooks_create201_response_data import WebhooksCreate201ResponseData as WebhooksCreate201ResponseData
from botix.models.webhooks_create_request import WebhooksCreateRequest as WebhooksCreateRequest
from botix.models.webhooks_list200_response import WebhooksList200Response as WebhooksList200Response
from botix.models.webhooks_test200_response import WebhooksTest200Response as WebhooksTest200Response
from botix.models.webhooks_test200_response_data import WebhooksTest200ResponseData as WebhooksTest200ResponseData
from botix.models.webhooks_update_request import WebhooksUpdateRequest as WebhooksUpdateRequest

