# coding: utf-8

# flake8: noqa

"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены. 

    The version of the OpenAPI document: 1.0.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "WebhooksApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Channel",
    "Chat",
    "Contact",
    "ContactWritable",
    "Error",
    "ErrorError",
    "MeResponse",
    "MeResponseData",
    "MeResponseDataLimits",
    "MeResponseDataRateLimit",
    "Message",
    "PublicV1ChannelsGet200Response",
    "PublicV1ChannelsGet200ResponseMeta",
    "PublicV1ChatsGet200Response",
    "PublicV1ContactsGet200Response",
    "PublicV1ContactsIdTagsPost200Response",
    "PublicV1ContactsIdTagsPost200ResponseData",
    "PublicV1ContactsIdTagsPostRequest",
    "PublicV1ContactsIdTagsTagDelete200Response",
    "PublicV1MessagesGet200Response",
    "PublicV1MessagesPost200Response",
    "PublicV1MessagesPost200ResponseData",
    "PublicV1MessagesPostRequest",
    "PublicV1MessagesPostRequestAttachmentsInner",
    "PublicV1ScenariosGet200Response",
    "PublicV1ScenariosIdRunPost200Response",
    "PublicV1ScenariosIdRunPost200ResponseData",
    "PublicV1ScenariosIdRunPostRequest",
    "PublicV1WebhooksGet200Response",
    "PublicV1WebhooksIdPutRequest",
    "PublicV1WebhooksIdTestPost200Response",
    "PublicV1WebhooksIdTestPost200ResponseData",
    "PublicV1WebhooksPost201Response",
    "PublicV1WebhooksPost201ResponseData",
    "PublicV1WebhooksPostRequest",
    "Scenario",
    "SuccessContact",
    "SuccessWithMeta",
    "SuccessWithMetaMeta",
    "Webhook",
    "WebhookEvent",
]

# import apis into sdk package
from botix.api.default_api import DefaultApi as DefaultApi
from botix.api.webhooks_api import WebhooksApi as WebhooksApi

# import ApiClient
from botix.api_response import ApiResponse as ApiResponse
from botix.api_client import ApiClient as ApiClient
from botix.configuration import Configuration as Configuration
from botix.exceptions import OpenApiException as OpenApiException
from botix.exceptions import ApiTypeError as ApiTypeError
from botix.exceptions import ApiValueError as ApiValueError
from botix.exceptions import ApiKeyError as ApiKeyError
from botix.exceptions import ApiAttributeError as ApiAttributeError
from botix.exceptions import ApiException as ApiException

# import models into sdk package
from botix.models.channel import Channel as Channel
from botix.models.chat import Chat as Chat
from botix.models.contact import Contact as Contact
from botix.models.contact_writable import ContactWritable as ContactWritable
from botix.models.error import Error as Error
from botix.models.error_error import ErrorError as ErrorError
from botix.models.me_response import MeResponse as MeResponse
from botix.models.me_response_data import MeResponseData as MeResponseData
from botix.models.me_response_data_limits import MeResponseDataLimits as MeResponseDataLimits
from botix.models.me_response_data_rate_limit import MeResponseDataRateLimit as MeResponseDataRateLimit
from botix.models.message import Message as Message
from botix.models.public_v1_channels_get200_response import PublicV1ChannelsGet200Response as PublicV1ChannelsGet200Response
from botix.models.public_v1_channels_get200_response_meta import PublicV1ChannelsGet200ResponseMeta as PublicV1ChannelsGet200ResponseMeta
from botix.models.public_v1_chats_get200_response import PublicV1ChatsGet200Response as PublicV1ChatsGet200Response
from botix.models.public_v1_contacts_get200_response import PublicV1ContactsGet200Response as PublicV1ContactsGet200Response
from botix.models.public_v1_contacts_id_tags_post200_response import PublicV1ContactsIdTagsPost200Response as PublicV1ContactsIdTagsPost200Response
from botix.models.public_v1_contacts_id_tags_post200_response_data import PublicV1ContactsIdTagsPost200ResponseData as PublicV1ContactsIdTagsPost200ResponseData
from botix.models.public_v1_contacts_id_tags_post_request import PublicV1ContactsIdTagsPostRequest as PublicV1ContactsIdTagsPostRequest
from botix.models.public_v1_contacts_id_tags_tag_delete200_response import PublicV1ContactsIdTagsTagDelete200Response as PublicV1ContactsIdTagsTagDelete200Response
from botix.models.public_v1_messages_get200_response import PublicV1MessagesGet200Response as PublicV1MessagesGet200Response
from botix.models.public_v1_messages_post200_response import PublicV1MessagesPost200Response as PublicV1MessagesPost200Response
from botix.models.public_v1_messages_post200_response_data import PublicV1MessagesPost200ResponseData as PublicV1MessagesPost200ResponseData
from botix.models.public_v1_messages_post_request import PublicV1MessagesPostRequest as PublicV1MessagesPostRequest
from botix.models.public_v1_messages_post_request_attachments_inner import PublicV1MessagesPostRequestAttachmentsInner as PublicV1MessagesPostRequestAttachmentsInner
from botix.models.public_v1_scenarios_get200_response import PublicV1ScenariosGet200Response as PublicV1ScenariosGet200Response
from botix.models.public_v1_scenarios_id_run_post200_response import PublicV1ScenariosIdRunPost200Response as PublicV1ScenariosIdRunPost200Response
from botix.models.public_v1_scenarios_id_run_post200_response_data import PublicV1ScenariosIdRunPost200ResponseData as PublicV1ScenariosIdRunPost200ResponseData
from botix.models.public_v1_scenarios_id_run_post_request import PublicV1ScenariosIdRunPostRequest as PublicV1ScenariosIdRunPostRequest
from botix.models.public_v1_webhooks_get200_response import PublicV1WebhooksGet200Response as PublicV1WebhooksGet200Response
from botix.models.public_v1_webhooks_id_put_request import PublicV1WebhooksIdPutRequest as PublicV1WebhooksIdPutRequest
from botix.models.public_v1_webhooks_id_test_post200_response import PublicV1WebhooksIdTestPost200Response as PublicV1WebhooksIdTestPost200Response
from botix.models.public_v1_webhooks_id_test_post200_response_data import PublicV1WebhooksIdTestPost200ResponseData as PublicV1WebhooksIdTestPost200ResponseData
from botix.models.public_v1_webhooks_post201_response import PublicV1WebhooksPost201Response as PublicV1WebhooksPost201Response
from botix.models.public_v1_webhooks_post201_response_data import PublicV1WebhooksPost201ResponseData as PublicV1WebhooksPost201ResponseData
from botix.models.public_v1_webhooks_post_request import PublicV1WebhooksPostRequest as PublicV1WebhooksPostRequest
from botix.models.scenario import Scenario as Scenario
from botix.models.success_contact import SuccessContact as SuccessContact
from botix.models.success_with_meta import SuccessWithMeta as SuccessWithMeta
from botix.models.success_with_meta_meta import SuccessWithMetaMeta as SuccessWithMetaMeta
from botix.models.webhook import Webhook as Webhook
from botix.models.webhook_event import WebhookEvent as WebhookEvent

