# coding: utf-8

# flake8: noqa
"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены. 

    The version of the OpenAPI document: 1.0.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from botix.models.channel import Channel
from botix.models.chat import Chat
from botix.models.contact import Contact
from botix.models.contact_writable import ContactWritable
from botix.models.error import Error
from botix.models.error_error import ErrorError
from botix.models.me_response import MeResponse
from botix.models.me_response_data import MeResponseData
from botix.models.me_response_data_limits import MeResponseDataLimits
from botix.models.me_response_data_rate_limit import MeResponseDataRateLimit
from botix.models.message import Message
from botix.models.public_v1_channels_get200_response import PublicV1ChannelsGet200Response
from botix.models.public_v1_channels_get200_response_meta import PublicV1ChannelsGet200ResponseMeta
from botix.models.public_v1_chats_get200_response import PublicV1ChatsGet200Response
from botix.models.public_v1_contacts_get200_response import PublicV1ContactsGet200Response
from botix.models.public_v1_contacts_id_tags_post200_response import PublicV1ContactsIdTagsPost200Response
from botix.models.public_v1_contacts_id_tags_post200_response_data import PublicV1ContactsIdTagsPost200ResponseData
from botix.models.public_v1_contacts_id_tags_post_request import PublicV1ContactsIdTagsPostRequest
from botix.models.public_v1_contacts_id_tags_tag_delete200_response import PublicV1ContactsIdTagsTagDelete200Response
from botix.models.public_v1_messages_get200_response import PublicV1MessagesGet200Response
from botix.models.public_v1_messages_post200_response import PublicV1MessagesPost200Response
from botix.models.public_v1_messages_post200_response_data import PublicV1MessagesPost200ResponseData
from botix.models.public_v1_messages_post_request import PublicV1MessagesPostRequest
from botix.models.public_v1_messages_post_request_attachments_inner import PublicV1MessagesPostRequestAttachmentsInner
from botix.models.public_v1_scenarios_get200_response import PublicV1ScenariosGet200Response
from botix.models.public_v1_scenarios_id_run_post200_response import PublicV1ScenariosIdRunPost200Response
from botix.models.public_v1_scenarios_id_run_post200_response_data import PublicV1ScenariosIdRunPost200ResponseData
from botix.models.public_v1_scenarios_id_run_post_request import PublicV1ScenariosIdRunPostRequest
from botix.models.public_v1_webhooks_get200_response import PublicV1WebhooksGet200Response
from botix.models.public_v1_webhooks_id_put_request import PublicV1WebhooksIdPutRequest
from botix.models.public_v1_webhooks_id_test_post200_response import PublicV1WebhooksIdTestPost200Response
from botix.models.public_v1_webhooks_id_test_post200_response_data import PublicV1WebhooksIdTestPost200ResponseData
from botix.models.public_v1_webhooks_post201_response import PublicV1WebhooksPost201Response
from botix.models.public_v1_webhooks_post201_response_data import PublicV1WebhooksPost201ResponseData
from botix.models.public_v1_webhooks_post_request import PublicV1WebhooksPostRequest
from botix.models.scenario import Scenario
from botix.models.success_contact import SuccessContact
from botix.models.success_with_meta import SuccessWithMeta
from botix.models.success_with_meta_meta import SuccessWithMetaMeta
from botix.models.webhook import Webhook
from botix.models.webhook_event import WebhookEvent

