# coding: utf-8

# flake8: noqa
"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента. 

    The version of the OpenAPI document: 1.1.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from botix.models.bulk_result import BulkResult
from botix.models.bulk_result_data import BulkResultData
from botix.models.bulk_result_data_results_inner import BulkResultDataResultsInner
from botix.models.channel import Channel
from botix.models.channels_list200_response import ChannelsList200Response
from botix.models.channels_list200_response_meta import ChannelsList200ResponseMeta
from botix.models.chat import Chat
from botix.models.chats_list200_response import ChatsList200Response
from botix.models.contact import Contact
from botix.models.contact_writable import ContactWritable
from botix.models.contacts_add_tag200_response import ContactsAddTag200Response
from botix.models.contacts_add_tag200_response_data import ContactsAddTag200ResponseData
from botix.models.contacts_add_tag_request import ContactsAddTagRequest
from botix.models.contacts_bulk_create_request import ContactsBulkCreateRequest
from botix.models.contacts_bulk_update_request import ContactsBulkUpdateRequest
from botix.models.contacts_bulk_update_request_updates_inner import ContactsBulkUpdateRequestUpdatesInner
from botix.models.contacts_list200_response import ContactsList200Response
from botix.models.contacts_remove_tag200_response import ContactsRemoveTag200Response
from botix.models.error import Error
from botix.models.error_error import ErrorError
from botix.models.me_response import MeResponse
from botix.models.me_response_data import MeResponseData
from botix.models.me_response_data_limits import MeResponseDataLimits
from botix.models.me_response_data_rate_limit import MeResponseDataRateLimit
from botix.models.message import Message
from botix.models.messages_bulk_send200_response import MessagesBulkSend200Response
from botix.models.messages_bulk_send200_response_data import MessagesBulkSend200ResponseData
from botix.models.messages_bulk_send200_response_data_results_inner import MessagesBulkSend200ResponseDataResultsInner
from botix.models.messages_bulk_send_request import MessagesBulkSendRequest
from botix.models.messages_bulk_send_request_messages_inner import MessagesBulkSendRequestMessagesInner
from botix.models.messages_bulk_send_request_messages_inner_attachments_inner import MessagesBulkSendRequestMessagesInnerAttachmentsInner
from botix.models.messages_list200_response import MessagesList200Response
from botix.models.messages_send200_response import MessagesSend200Response
from botix.models.messages_send200_response_data import MessagesSend200ResponseData
from botix.models.messages_send_request import MessagesSendRequest
from botix.models.messages_send_request_attachments_inner import MessagesSendRequestAttachmentsInner
from botix.models.scenario import Scenario
from botix.models.scenarios_list200_response import ScenariosList200Response
from botix.models.scenarios_run200_response import ScenariosRun200Response
from botix.models.scenarios_run200_response_data import ScenariosRun200ResponseData
from botix.models.scenarios_run_request import ScenariosRunRequest
from botix.models.success_contact import SuccessContact
from botix.models.success_with_meta import SuccessWithMeta
from botix.models.success_with_meta_meta import SuccessWithMetaMeta
from botix.models.webhook import Webhook
from botix.models.webhook_event import WebhookEvent
from botix.models.webhooks_create201_response import WebhooksCreate201Response
from botix.models.webhooks_create201_response_data import WebhooksCreate201ResponseData
from botix.models.webhooks_create_request import WebhooksCreateRequest
from botix.models.webhooks_list200_response import WebhooksList200Response
from botix.models.webhooks_test200_response import WebhooksTest200Response
from botix.models.webhooks_test200_response_data import WebhooksTest200ResponseData
from botix.models.webhooks_update_request import WebhooksUpdateRequest

