# coding: utf-8

"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента. 

    The version of the OpenAPI document: 1.1.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Contact(BaseModel):
    """
    Contact
    """ # noqa: E501
    id: Optional[StrictInt] = None
    project_id: Optional[StrictInt] = None
    first_name: Optional[StrictStr] = None
    last_name: Optional[StrictStr] = None
    phone: Optional[StrictStr] = None
    email: Optional[StrictStr] = None
    telegram_user_id: Optional[StrictInt] = None
    telegram_username: Optional[StrictStr] = None
    whatsapp_phone: Optional[StrictStr] = None
    vk_user_id: Optional[StrictInt] = None
    avatar_url: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    timezone: Optional[StrictStr] = None
    language: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["ru"]})
    birthday: Optional[date] = None
    tags: Optional[List[StrictStr]] = None
    lead_status: Optional[StrictStr] = None
    messages_count: Optional[StrictInt] = None
    last_message_at: Optional[datetime] = None
    last_channel: Optional[StrictStr] = Field(default=None, description="Последний канал, через который контакт писал (telegram/vk/widget/...)")
    first_message_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    widget_session_id: Optional[StrictStr] = Field(default=None, description="Идентификатор сессии в виджете (для канала widget)")
    __properties: ClassVar[List[str]] = ["id", "project_id", "first_name", "last_name", "phone", "email", "telegram_user_id", "telegram_username", "whatsapp_phone", "vk_user_id", "avatar_url", "city", "timezone", "language", "birthday", "tags", "lead_status", "messages_count", "last_message_at", "last_channel", "first_message_at", "created_at", "updated_at", "widget_session_id"]

    @field_validator('lead_status')
    def lead_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['new', 'warm', 'hot', 'client', 'lost']):
            raise ValueError("must be one of enum values ('new', 'warm', 'hot', 'client', 'lost')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Contact from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['first_name'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['last_name'] = None

        # set to None if phone (nullable) is None
        # and model_fields_set contains the field
        if self.phone is None and "phone" in self.model_fields_set:
            _dict['phone'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if telegram_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.telegram_user_id is None and "telegram_user_id" in self.model_fields_set:
            _dict['telegram_user_id'] = None

        # set to None if telegram_username (nullable) is None
        # and model_fields_set contains the field
        if self.telegram_username is None and "telegram_username" in self.model_fields_set:
            _dict['telegram_username'] = None

        # set to None if whatsapp_phone (nullable) is None
        # and model_fields_set contains the field
        if self.whatsapp_phone is None and "whatsapp_phone" in self.model_fields_set:
            _dict['whatsapp_phone'] = None

        # set to None if vk_user_id (nullable) is None
        # and model_fields_set contains the field
        if self.vk_user_id is None and "vk_user_id" in self.model_fields_set:
            _dict['vk_user_id'] = None

        # set to None if avatar_url (nullable) is None
        # and model_fields_set contains the field
        if self.avatar_url is None and "avatar_url" in self.model_fields_set:
            _dict['avatar_url'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['city'] = None

        # set to None if timezone (nullable) is None
        # and model_fields_set contains the field
        if self.timezone is None and "timezone" in self.model_fields_set:
            _dict['timezone'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if birthday (nullable) is None
        # and model_fields_set contains the field
        if self.birthday is None and "birthday" in self.model_fields_set:
            _dict['birthday'] = None

        # set to None if last_message_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_message_at is None and "last_message_at" in self.model_fields_set:
            _dict['last_message_at'] = None

        # set to None if last_channel (nullable) is None
        # and model_fields_set contains the field
        if self.last_channel is None and "last_channel" in self.model_fields_set:
            _dict['last_channel'] = None

        # set to None if first_message_at (nullable) is None
        # and model_fields_set contains the field
        if self.first_message_at is None and "first_message_at" in self.model_fields_set:
            _dict['first_message_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if widget_session_id (nullable) is None
        # and model_fields_set contains the field
        if self.widget_session_id is None and "widget_session_id" in self.model_fields_set:
            _dict['widget_session_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Contact from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project_id": obj.get("project_id"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "phone": obj.get("phone"),
            "email": obj.get("email"),
            "telegram_user_id": obj.get("telegram_user_id"),
            "telegram_username": obj.get("telegram_username"),
            "whatsapp_phone": obj.get("whatsapp_phone"),
            "vk_user_id": obj.get("vk_user_id"),
            "avatar_url": obj.get("avatar_url"),
            "city": obj.get("city"),
            "timezone": obj.get("timezone"),
            "language": obj.get("language"),
            "birthday": obj.get("birthday"),
            "tags": obj.get("tags"),
            "lead_status": obj.get("lead_status"),
            "messages_count": obj.get("messages_count"),
            "last_message_at": obj.get("last_message_at"),
            "last_channel": obj.get("last_channel"),
            "first_message_at": obj.get("first_message_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "widget_session_id": obj.get("widget_session_id")
        })
        return _obj


