# coding: utf-8

"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента. 

    The version of the OpenAPI document: 1.1.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from botix.models.message import Message
from botix.models.success_with_meta_meta import SuccessWithMetaMeta
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MessagesList200Response(BaseModel):
    """
    MessagesList200Response
    """ # noqa: E501
    success: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [True]})
    data: Optional[List[Message]] = None
    meta: Optional[SuccessWithMetaMeta] = None
    __properties: ClassVar[List[str]] = ["success", "data", "meta"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MessagesList200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item_data in self.data:
                if _item_data:
                    _items.append(_item_data.to_dict())
            _dict['data'] = _items
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MessagesList200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "data": [Message.from_dict(_item) for _item in obj["data"]] if obj.get("data") is not None else None,
            "meta": SuccessWithMetaMeta.from_dict(obj["meta"]) if obj.get("meta") is not None else None
        })
        return _obj


