# coding: utf-8

"""
    BOTIX Public API

    Публичный программный интерфейс платформы BOTIX (botix.pro) — позволяет интеграторам и сторонним разработчикам встраивать функционал BOTIX в свои продукты: магазины, CRM, мобильные приложения, бэкенды.  **Авторизация:** заголовок `Authorization: Bearer btx_live_…`. Каждый ключ привязан к одному `project_id`. Каждый ключ имеет список `scopes` — операций, которые им разрешены. Без нужного scope — `403 INSUFFICIENT_SCOPE`.  **Гейтинг по тарифу:** - тариф без `api_enabled` — `403 API_NOT_AVAILABLE_ON_PLAN` - триальный тариф (`api_write_enabled=0`) — read-only, POST/PUT/PATCH/DELETE → `403 TRIAL_READ_ONLY` - лимиты `api_rate_per_minute` / `api_rate_per_day` — из настроек тарифа (см. ЛК `/billing`)  **Стандарт ответов:** обёртка `{success, data, meta}` для успеха и `{success:false, error:{code,message,details}}` для ошибки.  **Версионирование:** `/public/v1/*` фиксирован. Новые поля в ответах могут добавляться, удаление/смена типов запрещены.  ## Что нового в 1.1.0 (2026-05-22)  - **Rate-limit заголовки** во всех ответах: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`. На 429 — дополнительно `Retry-After`. - **Cursor-based пагинация** — query-параметр `cursor` + поле `meta.next_cursor` параллельно с существующим `page`/`per_page` (старые клиенты не ломаются). - **Bulk endpoints** для интеграторов: `POST /contacts/bulk-create`, `POST /messages/bulk-send`, `POST /contacts/bulk-update` (до 100 операций за запрос, частичный успех).  Изменения обратно-совместимые: все endpoint v1.0 работают без правок на стороне клиента. 

    The version of the OpenAPI document: 1.1.0
    Contact: hello@botix.pro
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebhookEvent(str, Enum):
    """
    WebhookEvent
    """

    """
    allowed enum values
    """
    CONTACT_DOT_CREATED = 'contact.created'
    CONTACT_DOT_UPDATED = 'contact.updated'
    CONTACT_DOT_DELETED = 'contact.deleted'
    CONTACT_DOT_TAGGED = 'contact.tagged'
    MESSAGE_DOT_RECEIVED = 'message.received'
    MESSAGE_DOT_SENT = 'message.sent'
    CHAT_DOT_OPENED = 'chat.opened'
    CHAT_DOT_CLOSED = 'chat.closed'
    CHAT_DOT_ASSIGNED = 'chat.assigned'
    SCENARIO_DOT_STARTED = 'scenario.started'
    SCENARIO_DOT_COMPLETED = 'scenario.completed'
    SCENARIO_DOT_FAILED = 'scenario.failed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookEvent from a JSON string"""
        return cls(json.loads(json_str))


